version: "3.3"

services:
  api:
    image: "ghcr.io/ratiscrum-v2/rts-api:main"
    restart: always
    ports:
      - 8000:80
    environment:
      NODE_ENV: production
      API_PORT: 80
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: 5432
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      S3_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      S3_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      S3_ENDPOINT: minio:9000
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
  postgres:
    image: "postgis/postgis"
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname=${DB_NAME}", "--host=localhost", "--username=${DB_USER}"]
      timeout: 10s
      retries: 10
  minio:
    image: minio/minio
    volumes:
    - ${MINIO_PATH}:/data
    ports:
    - 9000:9000
    - 9001:9001
    environment:
    - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
    command:
    - server
    - /data
    - --console-address
    - ":9001"
